### ISSUE TITLE
Question: Question regarding the snap

### ISSUE THREAD

**Issue by soumyaDghosh** [canonical/rustup-snap#1]
What's the need to symlink the binaries with rustup. Is there any special issue to address. Can you kindly explain? I am trying to understand this snap to use in my snaps. Thanks and Thanks for recreating this.

**Comment by liushuyu** [comment]
> What's the need to symlink the binaries with rustup. Is there any special issue to address.

Hi, this is because `rustup` is a launcher. It will try to determine which binary to launch by looking at how you invoke it. If you invoke the `rustup` binary through a symlink with the name `rustc`, then `rustup` will launch `rustc`.

You need to use `rustup` as a launcher if you want to use any toolchain binaries installed by it.
